---
name: CICD (PR)
on:
    pull_request:
        branches: [main]
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
  deploy-table-definitions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate Docker to GCR
      run: |
        echo "$SERVICE_ACCOUNT_DEV" > sa_key.json
        cat sa_key.json | docker login -u _json_key --password-stdin https://gcr.io
        rm sa_key.json
      env:
        SERVICE_ACCOUNT_DEV: ${{ secrets.SERVICE_ACCOUNT_DEV }}

    - name: Run Docker image
      run: |
        echo "$SERVICE_ACCOUNT_DEV" > /tmp/credentials.json
        docker run \
          -v $PWD:/app \
          -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json \
          gcr.io/nansen-blockchain-etl-dev/evmchain-etl-parse:pr-350 \
          --project nansen-blockchain-etl-dev
        rm /tmp/credentials.json
      env:
        SERVICE_ACCOUNT_DEV: ${{ secrets.SERVICE_ACCOUNT_DEV }}