name: pyTest

on: 
  pull_request
  

jobs:
  test:
    runs-on: ubuntu-latest
    name: Validate Json Files in parse Directory
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Run pyTest to Validate JSON Files
        run: pytest
